name: Cucumber Test Execution

on:
  push:
    branches: [ "selenium" ]
  workflow_dispatch:  # Enables manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests with Maven
      run: mvn clean test

    - name: Store Cucumber Reports
      run: |
        mkdir -p cucumber-reports
        cp -r target/cucumber-reports/*.html cucumber-reports/
    
    - name: Upload Cucumber Reports as an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports
        path: cucumber-reports/

  deploy-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Test Reports
      uses: actions/download-artifact@v4
      with:
        name: cucumber-reports
        path: cucumber-reports

    - name: Deploy Reports to GitHub Pages
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git checkout gh-pages
        cp -r cucumber-reports/* .
        git add .
        git commit -m "📊 Update Cucumber Report"
        git push origin gh-pages
